use crate::core::models::{JournalEntry, LedgerScope, ScenarioDefinition, ScenarioAssumption};

pub struct ScenarioManager;

impl ScenarioManager {
    /// Creates a scenario-projected ledger by cloning the actual records and applying strategic mutations.
    /// This is the core 'Strategic Sandbox' where 'What-if' cases are processed without touching real books.
    pub fn project_scenario(
        definition: ScenarioDefinition,
        actual_ledger: Vec<JournalEntry>,
    ) -> Vec<JournalEntry> {
        let mut scenario_ledger = Vec::new();

        // 1. Process Assumptions (Mutation Map)
        let revenue_mult = Self::get_assumption(&definition.assumptions, "revenue_multiplier", 1.0);
        let expense_mult = Self::get_assumption(&definition.assumptions, "expense_multiplier", 1.0);
        let fixed_cost_delta = Self::get_assumption(&definition.assumptions, "fixed_cost_delta", 0.0);

        for mut entry in actual_ledger {
            // Only Clone 'Actual' entries for the new Scenario space
            if entry.scope != LedgerScope::Actual { continue; }

            // 2. Identify Entry Type & Mutate (Scenario Logic)
            if entry.entry_type == "Revenue" {
                entry.amount *= revenue_mult;
                entry.vat *= revenue_mult;
                entry.description = format!("[SCENARIO: {}] {}", definition.name, entry.description);
            } else if entry.entry_type == "Expense" {
                entry.amount *= expense_mult;
                entry.vat *= expense_mult;
                
                // Add fixed cost delta to specific accounts (e.g. Rent, Cloud Infrastructure)
                if entry.debit_account.contains("AWS") || entry.debit_account.contains("Google") {
                    entry.amount += fixed_cost_delta;
                }
            }

            // 3. Seal with Scenario Metadata (The 'Wall' of isolation)
            entry.id = format!("SCENARIO-{}-{}", definition.id, entry.id);
            entry.scope = LedgerScope::Scenario;
            entry.scenario_id = Some(definition.id.clone());

            scenario_ledger.push(entry);
        }

        scenario_ledger
    }

    /// Helper to safely retrieve assumptions
    fn get_assumption(assumptions: &[ScenarioAssumption], key: &str, default: f64) -> f64 {
        assumptions.iter()
            .find(|a| a.key == key)
            .map(|a| a.value)
            .unwrap_or(default)
    }

    /// Generates Additional Strategic Entries (e.g., simulated New Investment)
    pub fn inject_strategic_event(
        scenario_id: String,
        description: String,
        amount: f64,
        debit_account: &str,
        credit_account: &str,
    ) -> JournalEntry {
        JournalEntry {
            id: format!("EVENT-{}-{}", scenario_id, uuid::Uuid::new_v4()),
            date: chrono::Local::now().format("%Y-%m-%d").to_string(), // Future events logic could be more complex
            description,
            vendor: None,
            debit_account: debit_account.to_string(),
            credit_account: credit_account.to_string(),
            amount,
            vat: 0.0,
            entry_type: "ScenarioEvent".to_string(),
            status: "Simulation".to_string(), // Explicit status for scenario events
            tax_code: None,
            version: 1,
            last_modified_by: Some("ScenarioManager".to_string()),
            attachment_url: None,
            ocr_data: None,
            compliance_context: Some("Automated Strategic Event".to_string()),
            tax_base_amount: None,
            audit_trail: vec!["Generated by ScenarioManager".to_string()],
            parse_status: None,
            raw_data_snapshot: None,
            transaction_group_id: None,
            employee_tags: vec![],
            is_insurance_part: false,
            scope: LedgerScope::Scenario,
            scenario_id: Some(scenario_id),
        }
    }
}
